plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:path/:basename:output_ext

safe: false

liquid:
  error_mode: strict
  strict_filters: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

generators:
  - LetterPageGenerator