repository: junsan1/junsan1.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - hash_assign

permalink: /:path/:basename:output_ext

safe: false

liquid:
  error_mode: strict
  strict_filters: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - "*/locales.yml"

generators:
  - LetterPageGenerator